/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JPanel;

/**
 *
 * @author Chenhai
 */
public final class Dashboard extends javax.swing.JFrame {
    
    private static Dashboard dashboard;

    /**
     * Creates new form Dashboard
     */
    private JPanel home,faculty,department,classroom,course,instructor,student,timetable;
    
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
        controlladd();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBar = new javax.swing.JPanel();
        jlMinimize = new javax.swing.JLabel();
        jlClose = new javax.swing.JLabel();
        jpMenu = new javax.swing.JPanel();
        jpFaculty = new javax.swing.JPanel();
        jlFacultyIcon = new javax.swing.JLabel();
        jlFaculty = new javax.swing.JLabel();
        jpDepartment = new javax.swing.JPanel();
        jlDepartmentIcon = new javax.swing.JLabel();
        jlDepartment = new javax.swing.JLabel();
        jpClassroom = new javax.swing.JPanel();
        jlClassroomIcon = new javax.swing.JLabel();
        jlClassroom = new javax.swing.JLabel();
        jpCourse = new javax.swing.JPanel();
        jlCourseIcon = new javax.swing.JLabel();
        jlCourse = new javax.swing.JLabel();
        jpInstructor = new javax.swing.JPanel();
        jlInstructorIcon = new javax.swing.JLabel();
        jlInstructor = new javax.swing.JLabel();
        jSeparatorBar = new javax.swing.JSeparator();
        jpStudent = new javax.swing.JPanel();
        jlStudentIcon = new javax.swing.JLabel();
        jlStudent = new javax.swing.JLabel();
        jpTimetable = new javax.swing.JPanel();
        jlTimetableIcon = new javax.swing.JLabel();
        jlTimetable = new javax.swing.JLabel();
        jpReport = new javax.swing.JPanel();
        jlReportIcon = new javax.swing.JLabel();
        jlReport = new javax.swing.JLabel();
        jpProfile = new javax.swing.JPanel();
        jlProfileIcon = new javax.swing.JLabel();
        jlProfile = new javax.swing.JLabel();
        jpSetting = new javax.swing.JPanel();
        jlSettingIcon = new javax.swing.JLabel();
        jlSetting = new javax.swing.JLabel();
        jpAbout = new javax.swing.JPanel();
        jlAboutIcon = new javax.swing.JLabel();
        jlAbout = new javax.swing.JLabel();
        jpLogout = new javax.swing.JPanel();
        jlLogoutIcon = new javax.swing.JLabel();
        jlLogout = new javax.swing.JLabel();
        jpHome = new javax.swing.JPanel();
        jlHomeIcon = new javax.swing.JLabel();
        jlHome = new javax.swing.JLabel();
        jpIteam = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Dashboard"); // NOI18N
        setUndecorated(true);

        jpBar.setBackground(new java.awt.Color(31, 58, 146));

        jlMinimize.setBackground(new java.awt.Color(31, 58, 146));
        jlMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/barform/icons8_minus_math_20px.png"))); // NOI18N
        jlMinimize.setName("Minimize"); // NOI18N
        jlMinimize.setOpaque(true);
        jlMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseLabelClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseLabelEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseLabelExited(evt);
            }
        });

        jlClose.setBackground(new java.awt.Color(31, 58, 146));
        jlClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/barform/icons8_multiply_20px.png"))); // NOI18N
        jlClose.setName("Exit"); // NOI18N
        jlClose.setOpaque(true);
        jlClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseLabelClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseLabelEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseLabelExited(evt);
            }
        });

        javax.swing.GroupLayout jpBarLayout = new javax.swing.GroupLayout(jpBar);
        jpBar.setLayout(jpBarLayout);
        jpBarLayout.setHorizontalGroup(
            jpBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jlClose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpBarLayout.setVerticalGroup(
            jpBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlClose)
            .addComponent(jlMinimize)
        );

        jpMenu.setBackground(new java.awt.Color(31, 58, 146));

        jpFaculty.setBackground(new java.awt.Color(31, 58, 146));
        jpFaculty.setName("Faculty"); // NOI18N
        jpFaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlFacultyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/Faculty.png"))); // NOI18N

        jlFaculty.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlFaculty.setForeground(new java.awt.Color(255, 255, 255));
        jlFaculty.setText("Faculty");

        javax.swing.GroupLayout jpFacultyLayout = new javax.swing.GroupLayout(jpFaculty);
        jpFaculty.setLayout(jpFacultyLayout);
        jpFacultyLayout.setHorizontalGroup(
            jpFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFacultyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlFacultyIcon)
                .addGap(18, 18, 18)
                .addComponent(jlFaculty)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFacultyLayout.setVerticalGroup(
            jpFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlFacultyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpDepartment.setBackground(new java.awt.Color(31, 58, 146));
        jpDepartment.setName("Department"); // NOI18N
        jpDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlDepartmentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/Department.png"))); // NOI18N

        jlDepartment.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlDepartment.setForeground(new java.awt.Color(255, 255, 255));
        jlDepartment.setText("Department");

        javax.swing.GroupLayout jpDepartmentLayout = new javax.swing.GroupLayout(jpDepartment);
        jpDepartment.setLayout(jpDepartmentLayout);
        jpDepartmentLayout.setHorizontalGroup(
            jpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlDepartmentIcon)
                .addGap(18, 18, 18)
                .addComponent(jlDepartment)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jpDepartmentLayout.setVerticalGroup(
            jpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlDepartmentIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpClassroom.setBackground(new java.awt.Color(31, 58, 146));
        jpClassroom.setName("Classroom"); // NOI18N
        jpClassroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlClassroomIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/Classroom.png"))); // NOI18N

        jlClassroom.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlClassroom.setForeground(new java.awt.Color(255, 255, 255));
        jlClassroom.setText("Classroom");

        javax.swing.GroupLayout jpClassroomLayout = new javax.swing.GroupLayout(jpClassroom);
        jpClassroom.setLayout(jpClassroomLayout);
        jpClassroomLayout.setHorizontalGroup(
            jpClassroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClassroomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlClassroomIcon)
                .addGap(18, 18, 18)
                .addComponent(jlClassroom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpClassroomLayout.setVerticalGroup(
            jpClassroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClassroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlClassroomIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpCourse.setBackground(new java.awt.Color(31, 58, 146));
        jpCourse.setName("Course"); // NOI18N
        jpCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlCourseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/Course.png"))); // NOI18N

        jlCourse.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlCourse.setForeground(new java.awt.Color(255, 255, 255));
        jlCourse.setText("Course");

        javax.swing.GroupLayout jpCourseLayout = new javax.swing.GroupLayout(jpCourse);
        jpCourse.setLayout(jpCourseLayout);
        jpCourseLayout.setHorizontalGroup(
            jpCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCourseIcon)
                .addGap(18, 18, 18)
                .addComponent(jlCourse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCourseLayout.setVerticalGroup(
            jpCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlCourseIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpInstructor.setBackground(new java.awt.Color(31, 58, 146));
        jpInstructor.setName("Instructor"); // NOI18N
        jpInstructor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlInstructorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/Instructor.png"))); // NOI18N

        jlInstructor.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlInstructor.setForeground(new java.awt.Color(255, 255, 255));
        jlInstructor.setText("Instructor");

        javax.swing.GroupLayout jpInstructorLayout = new javax.swing.GroupLayout(jpInstructor);
        jpInstructor.setLayout(jpInstructorLayout);
        jpInstructorLayout.setHorizontalGroup(
            jpInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInstructorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlInstructorIcon)
                .addGap(18, 18, 18)
                .addComponent(jlInstructor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpInstructorLayout.setVerticalGroup(
            jpInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlInstructorIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSeparatorBar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jSeparatorBar.setOpaque(true);

        jpStudent.setBackground(new java.awt.Color(31, 58, 146));
        jpStudent.setName("Student"); // NOI18N
        jpStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlStudentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/Student.png"))); // NOI18N

        jlStudent.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlStudent.setForeground(new java.awt.Color(255, 255, 255));
        jlStudent.setText("Student");

        javax.swing.GroupLayout jpStudentLayout = new javax.swing.GroupLayout(jpStudent);
        jpStudent.setLayout(jpStudentLayout);
        jpStudentLayout.setHorizontalGroup(
            jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlStudentIcon)
                .addGap(18, 18, 18)
                .addComponent(jlStudent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpStudentLayout.setVerticalGroup(
            jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlStudentIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpTimetable.setBackground(new java.awt.Color(31, 58, 146));
        jpTimetable.setName("Timetable"); // NOI18N
        jpTimetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlTimetableIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/Timetable.png"))); // NOI18N

        jlTimetable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlTimetable.setForeground(new java.awt.Color(255, 255, 255));
        jlTimetable.setText("Timetable");

        javax.swing.GroupLayout jpTimetableLayout = new javax.swing.GroupLayout(jpTimetable);
        jpTimetable.setLayout(jpTimetableLayout);
        jpTimetableLayout.setHorizontalGroup(
            jpTimetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTimetableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTimetableIcon)
                .addGap(18, 18, 18)
                .addComponent(jlTimetable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTimetableLayout.setVerticalGroup(
            jpTimetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTimetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlTimetableIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTimetable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpReport.setBackground(new java.awt.Color(31, 58, 146));
        jpReport.setName("Report"); // NOI18N
        jpReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlReportIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/Report.png"))); // NOI18N

        jlReport.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlReport.setForeground(new java.awt.Color(255, 255, 255));
        jlReport.setText("Report");

        javax.swing.GroupLayout jpReportLayout = new javax.swing.GroupLayout(jpReport);
        jpReport.setLayout(jpReportLayout);
        jpReportLayout.setHorizontalGroup(
            jpReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlReportIcon)
                .addGap(18, 18, 18)
                .addComponent(jlReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpReportLayout.setVerticalGroup(
            jpReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlReportIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlReport, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpProfile.setBackground(new java.awt.Color(31, 58, 146));
        jpProfile.setName("Profile"); // NOI18N
        jpProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/Profile.png"))); // NOI18N

        jlProfile.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlProfile.setForeground(new java.awt.Color(255, 255, 255));
        jlProfile.setText("Profile");

        javax.swing.GroupLayout jpProfileLayout = new javax.swing.GroupLayout(jpProfile);
        jpProfile.setLayout(jpProfileLayout);
        jpProfileLayout.setHorizontalGroup(
            jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlProfileIcon)
                .addGap(18, 18, 18)
                .addComponent(jlProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpProfileLayout.setVerticalGroup(
            jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlProfileIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpSetting.setBackground(new java.awt.Color(31, 58, 146));
        jpSetting.setName("Setting"); // NOI18N
        jpSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlSettingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/Setting.png"))); // NOI18N

        jlSetting.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlSetting.setForeground(new java.awt.Color(255, 255, 255));
        jlSetting.setText("Setting");

        javax.swing.GroupLayout jpSettingLayout = new javax.swing.GroupLayout(jpSetting);
        jpSetting.setLayout(jpSettingLayout);
        jpSettingLayout.setHorizontalGroup(
            jpSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSettingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlSettingIcon)
                .addGap(18, 18, 18)
                .addComponent(jlSetting)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jpSettingLayout.setVerticalGroup(
            jpSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlSettingIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpAbout.setBackground(new java.awt.Color(31, 58, 146));
        jpAbout.setName("About"); // NOI18N
        jpAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlAboutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/About.png"))); // NOI18N

        jlAbout.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlAbout.setForeground(new java.awt.Color(255, 255, 255));
        jlAbout.setText("About us");

        javax.swing.GroupLayout jpAboutLayout = new javax.swing.GroupLayout(jpAbout);
        jpAbout.setLayout(jpAboutLayout);
        jpAboutLayout.setHorizontalGroup(
            jpAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAboutIcon)
                .addGap(18, 18, 18)
                .addComponent(jlAbout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAboutLayout.setVerticalGroup(
            jpAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlAboutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpLogout.setBackground(new java.awt.Color(31, 58, 146));
        jpLogout.setName("Logout"); // NOI18N
        jpLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlLogoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/Logout.png"))); // NOI18N

        jlLogout.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlLogout.setForeground(new java.awt.Color(255, 255, 255));
        jlLogout.setText("Log out");

        javax.swing.GroupLayout jpLogoutLayout = new javax.swing.GroupLayout(jpLogout);
        jpLogout.setLayout(jpLogoutLayout);
        jpLogoutLayout.setHorizontalGroup(
            jpLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLogoutIcon)
                .addGap(18, 18, 18)
                .addComponent(jlLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpLogoutLayout.setVerticalGroup(
            jpLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlLogoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpHome.setBackground(new java.awt.Color(34, 167, 240));
        jpHome.setName("Home"); // NOI18N
        jpHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseExited(evt);
            }
        });

        jlHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu/Home.png"))); // NOI18N

        jlHome.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlHome.setForeground(new java.awt.Color(255, 255, 255));
        jlHome.setText("Home");

        javax.swing.GroupLayout jpHomeLayout = new javax.swing.GroupLayout(jpHome);
        jpHome.setLayout(jpHomeLayout);
        jpHomeLayout.setHorizontalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlHomeIcon)
                .addGap(18, 18, 18)
                .addComponent(jlHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpHomeLayout.setVerticalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlHomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlHome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpClassroom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparatorBar)
            .addComponent(jpStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpTimetable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpAbout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSeparatorBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpTimetable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpIteamLayout = new javax.swing.GroupLayout(jpIteam);
        jpIteam.setLayout(jpIteamLayout);
        jpIteamLayout.setHorizontalGroup(
            jpIteamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1081, Short.MAX_VALUE)
        );
        jpIteamLayout.setVerticalGroup(
            jpIteamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpIteam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpIteam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void controlladd(){
        home = new Home();
        faculty = new lstFaculty();
        department = new lstDepartment();
        classroom = new lstClassroom();
        course = new lstCourse();
        instructor = new lstInstructor();
        student = new lstStudent();
        timetable = new lstTimetable();
        jpIteam.setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        jpIteam.add(home, c);
        jpIteam.add(faculty, c);
        jpIteam.add(department,c);
        jpIteam.add(classroom,c);
        jpIteam.add(course,c);
        jpIteam.add(instructor,c);
        jpIteam.add(student,c);
        jpIteam.add(timetable,c);
        home.setVisible(true);
        faculty.setVisible(false);
        department.setVisible(false);
        classroom.setVisible(false);
        course.setVisible(false);
        instructor.setVisible(false);
        student.setVisible(false);
        timetable.setVisible(false);
    }
    
    private void OnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnMouseEntered
        String[] NameComponent = {"Home","Faculty","Department","Classroom","Course","Instructor","Student","Timetable","Report","Profile","Setting","About","Logout"};
        for (String NameComponent1 : NameComponent) {
            if (NameComponent1.equals(evt.getComponent().getName())) {
                evt.getComponent().setBackground(new Color(34,167,240));
            }
        }
    }//GEN-LAST:event_OnMouseEntered

    private void OnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnMouseExited
        String[] NameComponent = {"Home","Faculty","Department","Classroom","Course","Instructor","Student","Timetable","Report","Profile","Setting","About","Logout"};
        for (String NameComponent1 : NameComponent) {
            if (NameComponent1.equals(evt.getComponent().getName())) {
                evt.getComponent().setBackground(new Color(31,58,146));
            }
        }
    }//GEN-LAST:event_OnMouseExited

    private void OnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnMouseClicked
        
        home.setVisible(false);
        faculty.setVisible(false);
        department.setVisible(false);
        classroom.setVisible(false);
        course.setVisible(false);
        instructor.setVisible(false);
        student.setVisible(false);
        timetable.setVisible(false);
        switch(evt.getComponent().getName()){
            case "Home":{
                home.setVisible(true);
            }break;
            case "Faculty":{
                lstFaculty.dashboard = this;
                faculty.setVisible(true);
            }break;
            case "Department":{
                lstDepartment.dashboard = this;
                department.setVisible(true);
            }break;
            case "Classroom":{
                lstClassroom.dashboard = this;
                classroom.setVisible(true);

            }break;
            case "Course":{
                lstCourse.dashboard = this;
                course.setVisible(true);
            }break;
            case "Instructor":{
                lstInstructor.dashboard = this;
                instructor.setVisible(true);
            }break;
            case "Student":{
                lstStudent.dashboard = this;
                student.setVisible(true);
            }break;
            case "Timetable":{
                lstTimetable.dashboard = this;
                timetable.setVisible(true);
            }break;
            case "Report":{
            
            }break;
            case "Profile":{
//                new Signup().setVisible(true);
            }break;
            case "Setting":{
//                new Signup().setVisible(true);
            }break;
            case "About":{
                About.getInstance().setVisible(true);
                About.dashboard = this;
                this.setEnabled(false);
            }break;
            case "Logout":{
                //Create Message Box
                Signin.getInstance().setVisible(true);
                this.dispose();
            }break;
        }
    }//GEN-LAST:event_OnMouseClicked

    private void OnMouseLabelEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnMouseLabelEntered
        if(evt.getComponent().getName().equalsIgnoreCase("Exit")){
            evt.getComponent().setBackground(Color.red);
        }
        if(evt.getComponent().getName().equalsIgnoreCase("Minimize")){
            evt.getComponent().setBackground(new Color(153,153,153));
        }
    }//GEN-LAST:event_OnMouseLabelEntered

    private void OnMouseLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnMouseLabelClicked
        if(evt.getComponent().getName().equalsIgnoreCase("Exit")){
            //Create Messagebox =>> Yes No Ok
                
            //Call Loginform or Staying form Dashboard
            System.exit(0);
        }
        if(evt.getComponent().getName().equalsIgnoreCase("Minimize")){
            this.setState(ICONIFIED);
        }
    }//GEN-LAST:event_OnMouseLabelClicked

    private void OnMouseLabelExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnMouseLabelExited
        if(evt.getComponent().getName().equalsIgnoreCase("Exit")){
            evt.getComponent().setBackground(new Color(31,58,146));
        }
        if(evt.getComponent().getName().equalsIgnoreCase("Minimize")){
            evt.getComponent().setBackground(new Color(31,58,146));
        }
    }//GEN-LAST:event_OnMouseLabelExited

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparatorBar;
    private javax.swing.JLabel jlAbout;
    private javax.swing.JLabel jlAboutIcon;
    private javax.swing.JLabel jlClassroom;
    private javax.swing.JLabel jlClassroomIcon;
    private javax.swing.JLabel jlClose;
    private javax.swing.JLabel jlCourse;
    private javax.swing.JLabel jlCourseIcon;
    private javax.swing.JLabel jlDepartment;
    private javax.swing.JLabel jlDepartmentIcon;
    private javax.swing.JLabel jlFaculty;
    private javax.swing.JLabel jlFacultyIcon;
    private javax.swing.JLabel jlHome;
    private javax.swing.JLabel jlHomeIcon;
    private javax.swing.JLabel jlInstructor;
    private javax.swing.JLabel jlInstructorIcon;
    private javax.swing.JLabel jlLogout;
    private javax.swing.JLabel jlLogoutIcon;
    private javax.swing.JLabel jlMinimize;
    private javax.swing.JLabel jlProfile;
    private javax.swing.JLabel jlProfileIcon;
    private javax.swing.JLabel jlReport;
    private javax.swing.JLabel jlReportIcon;
    private javax.swing.JLabel jlSetting;
    private javax.swing.JLabel jlSettingIcon;
    private javax.swing.JLabel jlStudent;
    private javax.swing.JLabel jlStudentIcon;
    private javax.swing.JLabel jlTimetable;
    private javax.swing.JLabel jlTimetableIcon;
    private javax.swing.JPanel jpAbout;
    private javax.swing.JPanel jpBar;
    private javax.swing.JPanel jpClassroom;
    private javax.swing.JPanel jpCourse;
    private javax.swing.JPanel jpDepartment;
    private javax.swing.JPanel jpFaculty;
    private javax.swing.JPanel jpHome;
    private javax.swing.JPanel jpInstructor;
    private javax.swing.JPanel jpIteam;
    private javax.swing.JPanel jpLogout;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpProfile;
    private javax.swing.JPanel jpReport;
    private javax.swing.JPanel jpSetting;
    private javax.swing.JPanel jpStudent;
    private javax.swing.JPanel jpTimetable;
    // End of variables declaration//GEN-END:variables

    public static Dashboard getInstance(){
        if (dashboard == null) {
            dashboard = new Dashboard();
        }
        return dashboard;
    }
    
    public static void setEnable(boolean b){
        dashboard.setEnable(b);
    }
    
}
