/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Event.Connect_db;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Chenhai
 */
public class Signup extends javax.swing.JFrame {
    
    private static Signup signup;
    private static Connection con;
    private static Statement stm;
    private ResultSet rs;

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngSex = new javax.swing.ButtonGroup();
        jpDetailProject = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jlHeader = new javax.swing.JLabel();
        jlFullName = new javax.swing.JLabel();
        jtFullName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jbtSignup = new javax.swing.JButton();
        jbtSignin = new javax.swing.JButton();
        jlSex = new javax.swing.JLabel();
        jrbMale = new javax.swing.JRadioButton();
        jrbFemale = new javax.swing.JRadioButton();
        jlPosition = new javax.swing.JLabel();
        jtPoistion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jlUsername = new javax.swing.JLabel();
        jtUsername = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jlPassword = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jtPassword = new javax.swing.JPasswordField();
        jlRe_Password = new javax.swing.JLabel();
        jtRe_Password = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        jlExit = new javax.swing.JLabel();
        jlMinimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpDetailProject.setBackground(new java.awt.Color(0, 102, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Course Timetable");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Project");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo/TimetableLogo.png"))); // NOI18N
        jLabel9.setToolTipText("");

        jSeparator3.setOpaque(true);

        javax.swing.GroupLayout jpDetailProjectLayout = new javax.swing.GroupLayout(jpDetailProject);
        jpDetailProject.setLayout(jpDetailProjectLayout);
        jpDetailProjectLayout.setHorizontalGroup(
            jpDetailProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetailProjectLayout.createSequentialGroup()
                .addGroup(jpDetailProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDetailProjectLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jpDetailProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addGroup(jpDetailProjectLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jpDetailProjectLayout.setVerticalGroup(
            jpDetailProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetailProjectLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(31, 58, 146));

        jlHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlHeader.setForeground(new java.awt.Color(255, 255, 255));
        jlHeader.setText("Sign up");

        jlFullName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlFullName.setForeground(new java.awt.Color(255, 255, 255));
        jlFullName.setText("Full Name");

        jtFullName.setBackground(new java.awt.Color(31, 58, 146));
        jtFullName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtFullName.setForeground(new java.awt.Color(255, 255, 255));
        jtFullName.setToolTipText("Enter Your Full Name");
        jtFullName.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jbtSignup.setBackground(new java.awt.Color(31, 58, 147));
        jbtSignup.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbtSignup.setForeground(new java.awt.Color(255, 255, 255));
        jbtSignup.setText("Back");
        jbtSignup.setToolTipText("Back");
        jbtSignup.setName("Back"); // NOI18N
        jbtSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtSignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
        });

        jbtSignin.setBackground(new java.awt.Color(153, 0, 153));
        jbtSignin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbtSignin.setForeground(new java.awt.Color(255, 255, 255));
        jbtSignin.setText("Summit");
        jbtSignin.setToolTipText("Summit");
        jbtSignin.setName("Summit"); // NOI18N
        jbtSignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtSigninMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseEntered(evt);
            }
        });

        jlSex.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlSex.setForeground(new java.awt.Color(255, 255, 255));
        jlSex.setText("Sex");

        jrbMale.setBackground(new java.awt.Color(31, 58, 146));
        btngSex.add(jrbMale);
        jrbMale.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jrbMale.setForeground(new java.awt.Color(255, 255, 255));
        jrbMale.setSelected(true);
        jrbMale.setText("Male");
        jrbMale.setToolTipText("Male");

        jrbFemale.setBackground(new java.awt.Color(31, 58, 146));
        btngSex.add(jrbFemale);
        jrbFemale.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jrbFemale.setForeground(new java.awt.Color(255, 255, 255));
        jrbFemale.setText("Female");
        jrbFemale.setToolTipText("Female");

        jlPosition.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlPosition.setForeground(new java.awt.Color(255, 255, 255));
        jlPosition.setText("Position");

        jtPoistion.setBackground(new java.awt.Color(31, 58, 146));
        jtPoistion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtPoistion.setForeground(new java.awt.Color(255, 255, 255));
        jtPoistion.setToolTipText("Enter Your Position");
        jtPoistion.setBorder(null);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jlUsername.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlUsername.setForeground(new java.awt.Color(255, 255, 255));
        jlUsername.setText("Username");

        jtUsername.setBackground(new java.awt.Color(31, 58, 146));
        jtUsername.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtUsername.setForeground(new java.awt.Color(255, 255, 255));
        jtUsername.setToolTipText("Enter Your Username");
        jtUsername.setBorder(null);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jlPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlPassword.setForeground(new java.awt.Color(255, 255, 255));
        jlPassword.setText("Password");

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jtPassword.setBackground(new java.awt.Color(31, 58, 146));
        jtPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtPassword.setForeground(new java.awt.Color(255, 255, 255));
        jtPassword.setToolTipText("Enter Your Password");
        jtPassword.setBorder(null);

        jlRe_Password.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlRe_Password.setForeground(new java.awt.Color(255, 255, 255));
        jlRe_Password.setText("Re-Password");

        jtRe_Password.setBackground(new java.awt.Color(31, 58, 146));
        jtRe_Password.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtRe_Password.setForeground(new java.awt.Color(255, 255, 255));
        jtRe_Password.setToolTipText("Enter Your Password Again");
        jtRe_Password.setBorder(null);

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        jlExit.setBackground(new java.awt.Color(31, 58, 146));
        jlExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/barform/icons8_multiply_20px.png"))); // NOI18N
        jlExit.setToolTipText("Close");
        jlExit.setName("Exit"); // NOI18N
        jlExit.setOpaque(true);
        jlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseLabelClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseLabelEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseLabelExited(evt);
            }
        });

        jlMinimize.setBackground(new java.awt.Color(31, 58, 146));
        jlMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/barform/icons8_minus_math_20px.png"))); // NOI18N
        jlMinimize.setToolTipText("Minimize");
        jlMinimize.setName("Minimize"); // NOI18N
        jlMinimize.setOpaque(true);
        jlMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseLabelClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OnMouseLabelEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OnMouseLabelExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtRe_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jlHeader))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlFullName)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlRe_Password)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jlPosition)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(jtPoistion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jlUsername)
                                                .addGap(159, 159, 159))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jlPassword)
                                                .addGap(163, 163, 163)))
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jbtSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jlSex)
                            .addGap(18, 18, 18)
                            .addComponent(jrbMale)
                            .addGap(18, 18, 18)
                            .addComponent(jrbFemale))))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jlExit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlExit)
                    .addComponent(jlMinimize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlHeader)
                .addGap(21, 21, 21)
                .addComponent(jlFullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSex)
                    .addComponent(jrbMale)
                    .addComponent(jrbFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlPosition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPoistion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlRe_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtRe_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSignup)
                    .addComponent(jbtSignin))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpDetailProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDetailProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnMouseEntered
       Event.OnMouseButonControl.OnMouseEntered(evt);
    }//GEN-LAST:event_OnMouseEntered

    private void OnMouseLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnMouseLabelClicked
        if(evt.getComponent().getName().equalsIgnoreCase("Exit")){
            System.exit(0);
        }
        if(evt.getComponent().getName().equalsIgnoreCase("Minimize")){
            this.setState(JFrame.ICONIFIED);
        }
    }//GEN-LAST:event_OnMouseLabelClicked

    private void OnMouseLabelEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnMouseLabelEntered
        if(evt.getComponent().getName().equalsIgnoreCase("Exit")){
            evt.getComponent().setBackground(Color.red);
        }
        if(evt.getComponent().getName().equalsIgnoreCase("Minimize")){
            evt.getComponent().setBackground(new Color(37, 116, 168));
        }
    }//GEN-LAST:event_OnMouseLabelEntered

    private void OnMouseLabelExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnMouseLabelExited
        if(evt.getComponent().getName().equalsIgnoreCase("Exit")){
            evt.getComponent().setBackground(new Color(31,58,146));
        }
        if(evt.getComponent().getName().equalsIgnoreCase("Minimize")){
            evt.getComponent().setBackground(new Color(31,58,146));
        }
    }//GEN-LAST:event_OnMouseLabelExited

    private void jbtSigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSigninMouseClicked
        String fullName = jtFullName.getText();
        String userName = jtUsername.getText();
        String sex = getSex();
        String position = jtPoistion.getText();
        String password = jtPassword.getText();
        String re_password = jtRe_Password.getText();
        if (!fullName.isEmpty() && !userName.isEmpty() && !position.isEmpty()){
            if (!password.equals(re_password)) {
                JOptionPane.showMessageDialog(null, "Your password not match!", "Password not match", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                con = Connect_db.getConnection();
                stm = Connect_db.getStatement();
                try {
                    if (con != null && stm != null) {
                        rs = stm.executeQuery("SELECT user_name FROM tbUser");
                        ArrayList<String> arrayUsername = new ArrayList<>();
                        while(rs.next()){
                            arrayUsername.add(rs.getString(1));
                        }
                        if (!arrayUsername.contains(userName)) {
                            CallableStatement cs = con.prepareCall("{call dbo.insertUser("+fullName+","+userName+","+password+","+position+","+sex+","+null+","+null+","+null+")}");
                            cs.execute();
                            JOptionPane.showMessageDialog(null, "SignUp successfully!", "Successfully", JOptionPane.INFORMATION_MESSAGE);
                            new Signin().setVisible(true);
                            this.dispose();
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "This username has already!", "Signin", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                    else{
                        System.out.println("Connection null!");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Fullname, Username, Position\nCan't be null", "Enter information!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtSigninMouseClicked

    private void jbtSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSignupMouseClicked
        Signin.getInstance().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtSignupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngSex;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton jbtSignin;
    private javax.swing.JButton jbtSignup;
    private javax.swing.JLabel jlExit;
    private javax.swing.JLabel jlFullName;
    private javax.swing.JLabel jlHeader;
    private javax.swing.JLabel jlMinimize;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JLabel jlPosition;
    private javax.swing.JLabel jlRe_Password;
    private javax.swing.JLabel jlSex;
    private javax.swing.JLabel jlUsername;
    private javax.swing.JPanel jpDetailProject;
    private javax.swing.JRadioButton jrbFemale;
    private javax.swing.JRadioButton jrbMale;
    private javax.swing.JTextField jtFullName;
    private javax.swing.JPasswordField jtPassword;
    private javax.swing.JTextField jtPoistion;
    private javax.swing.JPasswordField jtRe_Password;
    private javax.swing.JTextField jtUsername;
    // End of variables declaration//GEN-END:variables

    private String getSex() {
        String sex = "";
        if(jrbMale.isSelected()){
            sex = "M";
        }
        if(jrbFemale.isSelected()){
            sex = "F";
        }
        return sex;
    }
    
    public static Signup getInstance(){
        if (signup == null) {
            signup = new Signup();
        }
        return signup;
    }
}
